# Generated by Django 3.2 on 2023-01-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_auto_20230108_1530"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ("name", "measurement_unit"),
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
    ]
