# Generated by Django 3.2 on 2023-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                help_text="Введите цвет в HEX (#rrggbb)",
                max_length=7,
                unique=True,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Введите slug",
                max_length=200,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
