# Generated by Django 3.2 on 2023-01-10 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_auto_20230105_1818"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                help_text="Введите цвет в HEX (#rrggbb)",
                max_length=7,
                unique=True,
                validators=[django.core.validators.RegexValidator("^#[a-fA-F0-9]{6}$")],
                verbose_name="Цвет",
            ),
        ),
    ]
