# Generated by Django 3.2 on 2023-01-10 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_alter_tag_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name",),
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                help_text="Введите цвет в RGB-формате (#rrggbb)",
                max_length=7,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[a-fA-F0-9]{6}$",
                        "Используйте RGB-формат для указания цвета (#AABBCC)",
                    )
                ],
                verbose_name="Цвет",
            ),
        ),
    ]
