# Generated by Django 3.2 on 2023-01-04 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Автоматически устанавливается текущая дата и время",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Выберите картинку",
                        upload_to="recipes/",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текстовое описание",
                        verbose_name="Текстовое описание",
                    ),
                ),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        help_text="Введите время приготовления в минутах",
                        verbose_name="Время приготовления в минутах",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Выберите из списка автора",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "carts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите пользователей, для добавления в их корзины",
                        related_name="cart_recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Корзины",
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите пользователей, для добавления в избранное",
                        related_name="favorite_recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Избранное",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
                "ordering": ("created",),
                "default_related_name": "%(class)ss",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Введите количество ингридиента",
                        verbose_name="Количество ингридиента",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        help_text="Выберите ингредиент рецепта",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="ingredients.ingredient",
                        verbose_name="Ингредиент рецепта",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="Выберите ингредиент рецепта",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="recipes.recipe",
                        verbose_name="Ингредиент рецепта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент рецепта",
                "verbose_name_plural": "Ингредиенты рецептов",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                help_text="Выберите ингредиенты",
                related_name="recipes",
                through="recipes.RecipeIngredient",
                to="ingredients.Ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите теги",
                related_name="recipes",
                to="tags.Tag",
                verbose_name="Теги",
            ),
        ),
    ]
