# Generated by Django 3.2 on 2023-01-06 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0002_auto_20230105_1818"),
        ("ingredients", "0001_initial"),
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcartrecipe",
            name="user",
            field=models.ForeignKey(
                help_text="Выберите из списка автора",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                help_text="Выберите из списка автора",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите пользователей, для добавления в избранное",
                related_name="favorite_recipes",
                through="recipes.FavoriteRecipe",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Избранное",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                help_text="Выберите ингредиенты",
                related_name="recipes",
                through="recipes.IngredientInRecipe",
                to="ingredients.Ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="shopping_carts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите пользователей, для добавления в их корзины",
                related_name="shopping_cart_recipes",
                through="recipes.ShoppingCartRecipe",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Корзины",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите теги",
                related_name="recipes",
                to="tags.Tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AddField(
            model_name="ingredientinrecipe",
            name="ingredient",
            field=models.ForeignKey(
                help_text="Выберите ингредиент рецепта",
                on_delete=django.db.models.deletion.RESTRICT,
                to="ingredients.ingredient",
                verbose_name="Ингредиент рецепта",
            ),
        ),
        migrations.AddField(
            model_name="ingredientinrecipe",
            name="recipe",
            field=models.ForeignKey(
                help_text="Выберите рецепт",
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AddField(
            model_name="favoriterecipe",
            name="recipe",
            field=models.ForeignKey(
                help_text="Выберите рецепт",
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AddField(
            model_name="favoriterecipe",
            name="user",
            field=models.ForeignKey(
                help_text="Выберите из списка автора",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcartrecipe",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="unique_shopping_cart"
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriterecipe",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="unique_favorite"
            ),
        ),
    ]
