# Generated by Django 3.2 on 2023-01-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
        ("recipes", "0002_alter_recipe_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecipeIngredient",
            new_name="IngredientInRecipe",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                help_text="Выберите картинку",
                upload_to="recipes/",
                verbose_name="Recipe image",
            ),
        ),
    ]
