# Generated by Django 3.2 on 2023-01-02 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0001_initial"),
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="carts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите пользователей, для добавления в их корзины",
                related_name="cart_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Корзины",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите пользователей, для добавления в избранное",
                related_name="favorite_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Избранное",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                help_text="Выберите количество ингредиентов",
                related_name="recipes",
                to="recipes.RecipeIngredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите теги",
                related_name="recipes",
                to="tags.Tag",
                verbose_name="Теги",
            ),
        ),
    ]
