# Generated by Django 3.2 on 2023-01-11 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0002_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favoriterecipe",
            options={
                "verbose_name": "Любимый рецепт",
                "verbose_name_plural": "Любимые рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcartrecipe",
            options={
                "verbose_name": "Рецепт в корзине пользователя",
                "verbose_name_plural": "Рецепты в корзинах пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="tagrecipe",
            options={
                "verbose_name": "Тег рецепта",
                "verbose_name_plural": "Теги рецептов",
            },
        ),
        migrations.AlterField(
            model_name="favoriterecipe",
            name="user",
            field=models.ForeignKey(
                help_text="Выберите из списка пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcartrecipe",
            name="user",
            field=models.ForeignKey(
                help_text="Выберите из списка пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
