# Generated by Django 3.2 on 2023-01-05 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_auto_20230105_0201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Введите количество ингридиента",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Укажите количество больше либо равное 1"
                    )
                ],
                verbose_name="Количество ингридиента",
            ),
        ),
    ]
