# Generated by Django 3.2 on 2023-01-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20230113_0003"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="favorites",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="shopping_carts",
        ),
    ]
