# Generated by Django 3.2 on 2023-01-02 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="author",
            field=models.ForeignKey(
                help_text="Выберите автора из списка",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                help_text="Выберите подписчика из списка",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
    ]
